### ISSUE TITLE
Incomplete Docs

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#10]
It would be really helpful if you could document the purpose of each non-obvious property of AirbrakeAppender, e.g.
- filtered_keys
- env
- supplementer
- secured
- varFilter
- etc.

**Comment by coderberry** [comment]
I'll enhance the README with a better explanation as to the parts of the appender being used in the Config.groovy file. As far as documenting the rest, I would think in-line documentation within the files themselves should suffice.

**Comment by jonspalmer** [comment]
The latest changes have much better docs. We can fill in the remaining details but they are mostly advanced usage.
