### ISSUE TITLE
stacktrace format

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#11]
By default the backtrace tab in airbrake shows the stacktrace in the following format

```
AirbrakeTestController.groovy:8:in `throwException'
PageFragmentCachingFilter.java:195:in `doFilter'
AbstractFilter.java:63:in `doFilter'
ThreadPoolExecutor.java:886:in `runTask'
ThreadPoolExecutor.java:908:in `run'
Thread.java:680:in `run'
```

Is it possible to show the fully-qualified class name instead? If so, IMO, this should be the default.

**Comment by jonspalmer** [comment]
I have this on my list to fix and I think its pretty easy.

**Comment by jonspalmer** [comment]
Pull request https://github.com/cavneb/airbrake-grails/pull/14
