### ISSUE TITLE
support sending caught exceptions to Airbrake

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#15]
Currently, the only errors that are sent to Airbrake are unhandled exceptions. However, it would be very useful to also be able to send handled errors. 

One possible way to support this would be for all calls to a Logger at the ERROR level (or above) to also send an error, e.g.

``` java
try {
  // some code that throws an exception

} catch (ex) {

  // because ex is logged at the error level, the error is sent to Airbrake
  log.error "Something bad happened", ex
}
```

So the idea is that in the code above ex is treated identically to an uncaught ex. A property could be added to AirbrakeAppender to indicate whether handled exceptions should also be logged, e.g.

```
    def airbrakeAppender = new grails.plugins.airbrake.AirbrakeAppender (
      name: 'airbrake',
      api_key: 'API_KEY',
      filtered_keys: ['password'],
      notify_handled_exceptions: org.apache.log4j.Level.ERROR
    )
```

The config above indicates that exceptions logged at the ERROR level and above should be sent to Airbrake. If this parameter is omitted, only uncaught exceptions are sent, to preserve compatability with previous plugin versions.

**Comment by ghost** [comment]
It could also be useful to be able to send an error to Airbrake when there's no exception at all, e.g. a library might use return codes rather than exceptions to indicate an error.

I don't yet have a satisfactory proposal for how this would work. One solution would be do add an AirbrakeNotificationService Spring bean which could be used to send errors that occur in taglibs, controllers, services, domain classes.

However, classes in src/groovy and src/java are not subject to dependency injection, so there is no elegant way to get a reference to this service therein.

**Comment by jonspalmer** [comment]
I actually have an implementation in the works that I expect to push in the next day or two that would solve this issue. I played with the idea of trapping all things logged at the Error level but I didn't like it much as you often don't get all the information (in particular the stacktrace) of a caught exception. Instead I have an airbrakeService that has two methods

```
def notify(Throwwable throwable)
def notify(String errorMessage)
```

the serivce is autowired as normal. If you have classes in src/java or src/groovy then you can wire up the DI pretty easily in resources.groovy.

**Comment by ghost** [comment]
Delighted to hear that you're already working on this, some suggestions follow.

>  I played with the idea of trapping all things logged at the Error level but I didn't like it much as you often don't get all the information (in particular the stacktrace) of a caught exception.

My proposal above was to only send errors to airbrake if one of the two-arg Logger methods is called, log.error(msg, throwable), which would guarantee the presence of an stacktrace.

> Instead I have an airbrakeService that has two methods

```
def notify(Throwwable throwable)
def notify(String errorMessage)
```

I'd prefer a single method with an optional Throwable arg

```
def notify (Object message, Throwable throwable = null)
```

> If you have classes in src/java or src/groovy then you can wire up the DI pretty easily in resources.groovy.

Surely you can only do that for classes that are created by Spring, i.e. if you instantiate these classes yourself, there's no way to DI them?

**Comment by jonspalmer** [comment]
> My proposal above was to only send errors to airbrake if one of the two-arg Logger methods is called, log.error(msg, throwable), which would guarantee the presence of an stacktrace.

That's an interesting wrinkle. Sadly by the time the appender is involved I'm not sure if you know the difference in how the log method was called. We ask the LoggingEvent if there is throwableInformation attached. I don't know what that returns if you call the two arg method as opposed to having an uncaught exception. I will test but its going to work one way or the other and there isn't likely to be much we can do about it if it works the wrong way. Crossing my fingers :)

> I'd prefer a single method with an optional Throwable arg
> I can see how that would be nice. However, its not very consistent with the behavior of the uncaught exception. In that mode the error message reported to Airbrake is the message of the Exception that was thrown. If you are manually calling 'notify' with a Throwable I would expect the same behavior. For consistency you therefore would never want to supply both a message and a Throwable. Hence two methods (and its worth noting that both the 'official' java airbrake appender and the Rails gem have a similar API)
> 
> Surely you can only do that for classes that are created by Spring, i.e. if you instantiate these classes yourself, there's no way to DI them?

You're probably right. I haven't spent a lot of time thinking about it and the need hasn't come up in our apps. I suspect if you really needed the service you could go through something ugly like the static appContext holders. I agree that just relying on logging with a throwable would be simpler to arrange.

**Comment by jonspalmer** [comment]
Good news after a quick test the two arg log.error method does trigger the existing appenders. So everything is good there. The interesting detail is that with the current implementation the message that is logged is completely ignored. I will look at how we might incorporate that. If that is possible then my 'consistency' argument above goes out the window. The only remaining question would be if we should support a configuration option to send logged errors without Throwables to airbrake or just have a service. I'm tempted to have both so that you have the flexibility to send things to Airbrake without logging them out. Stay tuned for a pull request sometime soon (and its going to be a really huge change that will need some code review.)

**Comment by ghost** [comment]
nice work, I'd be delighted to help in any way that I can

**Comment by jonspalmer** [comment]
I have much of what we discussed in pull request #16. Please check it out and let me know what you think. The refactoring was pretty extensive and while it has allowed much better tests some code review would be great.

**Comment by jonspalmer** [comment]
did you have a chance to look at the pull request?

**Comment by coderberry** [comment]
I just merged the pull request.. did you want me to package it and publish?

**Comment by jonspalmer** [comment]
I think that would be great. Probably worth a 0.8 version :)

**Comment by jonspalmer** [comment]
I will also work on the docs a little bit but that can be done separately from the bundling and release.

**Comment by ghost** [comment]
These new features are awesome, great job
