### ISSUE TITLE
unhandled exception message 

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#18]
The recent contribution that resolved [this issue](https://github.com/cavneb/airbrake-grails/pull/16) appears to have introduced a regression with the way unhandled exceptions are recorded. Previously, an action such as:

```
    def throwException() {
        throw new Exception("Power Cut")
    }
```

would cause an error to be logged in Airbrake with the message

> Power Cut

However, the Airbrake message that's now used for an exception such as the above is:

> Exception occurred when processing request: [GET] /ttt/test/throwException Power Cut. Stacktrace follows:

My own opinion is that the exception message (alone) is a more readable and appropriate message to use for each Airbrake error, and in the interest of backward compatibility, we should restore the previous behaviour.

**Comment by ghost** [comment]
I just tried using the plugin in a real application (until now I've been using a toy app) and the actual airbrake message generated for an unhandled exception was:

> 500: '/footer2' Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1 params: [action:serverError, controller:errors] session: Session Content: org.codehaus.groovy.grails.FLASH_SCOPE = org.codehaus.groovy.grails.web.servlet.GrailsFlashScope@7958264f myval = Something in the Session! visit = VisitBean [id: 135050693855874, location: Location [safePostalCode: 10178, localityUrlRep: Berlin, safeLocalityDisplay: Berlin, geo: 52.522x13.4161)], firstVisitCookieSetDuringVisit: true] password = super_secret_password isMobileBrowser = false 

This is almost useless, so I really think we should go back to using the exception message (unless there is no exception)

**Comment by jonspalmer** [comment]
I will fix

**Comment by ghost** [comment]
Great, I think it's just a matter of changing line 30 of GrailsNoticeBuilder from

```
def message = errorMessage ?:  throwable?.message
```

to

```
def message = throwable?.message ?: errorMessage
```

But you know better than I do.

**Comment by ghost** [comment]
On second thoughts, for a statement like

```
log.error("some msg", new Exception("exception msg"))
```

I think it would be fine to use either "some msg" or "exception msg" as the airbrake error message. Either would certainly be better than what we're getting at the moment. You could make an argument that using the first arg would be consistent with what happens when you set:

```
grails.plugins.airbrake.includeEventsWithoutExceptions = true
```

and generate an error with

```
log.error("something bad happened")
```

**Comment by jonspalmer** [comment]
This is fixed. We just need a new release of the plugin.

**Comment by ghost** [comment]
Thanks for resolving this so quickly. I've merged the changes into the Grails 1.3 branch. Do you know what version number you will release this as. I'm trying to keep the Grails 1.3 versions in synch with the corresponding version from the Grails 2 (master) branch.

**Comment by jonspalmer** [comment]
I bumped the version to 0.8.1. needs to be published but I don't have the credentials for that.

**Comment by coderberry** [comment]
I published the latest version. How can I give you credentials so you can publish without giving you my u/p?

**Comment by ghost** [comment]
I think if you can add people to a project by sending a mail to the mailing list (the same way you got permission to publish the plugin initially). They can then release with their own u/p.

**Comment by jonspalmer** [comment]
I'm not sure if there is a way. I will ask the grails dev-list or do some
digging as to how I can get rights to do it. Maybe we can just have some
common u/p just for publishing to Grails Central.

**Comment by ghost** [comment]
I'm pretty sure it is possible to add other devs to a plugin project as long as they're already registered plugin developers. It's such an obvious need, that it would be strange if it isn't supported.
