### ISSUE TITLE
Should we provide information for nested exceptions?

### ISSUE THREAD

**Issue by SpOOnman** [coderberry/airbrake-grails#25]
Currently airbrake plugin provides information only about  top-most exception. I think that we can make it better and provide information about all nested exceptions.

For example, consider hierarchy:

```
MyConnectionException("foo")
    +---IOException("bar")
        +---SocketException("baz")
```

I think that we can extend plugin so it reports:
- errorMessage - 3 messages joined with a newline: `foo\nbar\nbaz`
- errorClass - top-most exception class: MyConnectionException
- backtrace - whole backtrace of 3 exceptions from top-most to bottom-lowest

What do you think? I think it's reasonable and I can provide implementation along with tests.

**Comment by jonspalmer** [comment]
The challenge with this is that Airbrake uses the Exception name and message to provide its grouping. I'd worry that if we mangle the messages to include the nested exceptions it will struggle to perform a good grouping. 

However we should definitely by looking to include all the stack trace details of the nested exceptions. If that isn't happening we should fix it.

**Comment by jonspalmer** [comment]
Its important for exception grouping to keep the exception names consistent so they can be grouped by Airbrake. I don't think it makes sense to implement this change

**Comment by meltzow** [comment]
+1 for reopen it. 
a full backtrace with all exceptions ist needed. For example: we are using quartz. if a exception is thrown in a quartz job the fullbacktrace only contains :
<code>
GrailsJobFactory.java:111
JobRunShell.java:202
SimpleThreadPool.java:573
</code>
 so it not possible the where the exception is thrown

**Comment by jonspalmer** [comment]
PR with tests would be welcome.

**Comment by meltzow** [comment]
here is the PR. ;-)

**Comment by meltzow** [comment]
any idea, when you are able the merge the PR? We need this feature urgent and if the merging needs some time, we must use are own fork.
