### ISSUE TITLE
notifications sent synchronously by default

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#26]
According to the docs

> By default, notifications are sent to Airbrake asynchronously using a thread-pool of size 5.

However, my testing indicates that they are sent synchronously by default. You can verify this by creating a test project with a valid API key. Generate and error from this test project with a breakpoint set in the following method of `AirbrakeNotifier`

``` groovy
void sendNotice(Notice notice) {
    if (configuration.async) {
        configuration.async(notice, grailsApplication)
    } else {
        sendToAirbrake(notice)
    }
}
```

You'll see that by default the sendToAirbrake branch is executed which sends notices synchronously. The root cause of the problem is in `Configuration` where `async` is initialized

``` groovy
    private configureDefaultAsyncClosure(Map options) {
        def async = (options.async != null) ? options.async : true
        if (!(async instanceof Closure)) {

            ////////////////////////////////////////////////////////////////////////////////////////
            /////////////// problem is here async is falsey
            //////////////////////////////////////////////////////////////////////////////////////// 
            if (async == true ) {
                log.info "configureDefaultAsyncClosure create default async handler with threadPool"
                def threadPoolSize = options.asyncThreadPoolSize ?: 5
                threadPool = Executors.newFixedThreadPool(threadPoolSize)
                options.async = { notice, grailsApplication ->
                    log.debug "submitting notice to threadPool"
                    Runnable sendToAirbrake = {
                        grailsApplication.mainContext.airbrakeNotifier.sendToAirbrake(notice)
                    } as Runnable
                    threadPool.submit(sendToAirbrake)
                }
            } else {
                options.async = null
            }
        }
    }
```

If you add the config param

``` groovy
grails.plugins.airbrake.async = true
```

Then notifications are sent asynchronously, so maybe the docs just need to be changed to say that the default is synchronous, though IMO asynchronous would be a better default (which implies there's currently a bug).

**Comment by jonspalmer** [comment]
Seems like we should fix the bug with a default value of the config parameter. A Pull request would be much appreciated.

**Comment by ghost** [comment]
I guess this can be closed, or would you prefer to wait until the fix has been included in a release?
