### ISSUE TITLE
Docs should say that grails.plugins.airbrake stuff should be on error on log4j config

### ISSUE THREAD

**Issue by radeinla** [coderberry/airbrake-grails#29]
It was a little confusing at first when I decided to customize our logging configuration and left out the 'grails.plugins.airbrake' stuff then no more api calls were sent to the server. Just for being informed sake.

**Comment by radeinla** [comment]
Although I'm not entirely sure. I'll check it out some other time with an empty grails app later to verify if this was really the problem.

**Comment by jonspalmer** [comment]
I'm not sure I understand the problem. Perhaps you can provide your example config so we can look at it further.

**Comment by jonspalmer** [comment]
no further info here.
