### ISSUE TITLE
Make plugin more resilient to server unavailability

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#31]
It's possible that the client cannot contact the server, for example:
- in the case of a locally running server, the URL, port, etc. may have been incorrectly configured
- if using the public Airbrake server, it could be unavailable

If the server is unavailable, the plugin will try to send the notice to the server each time an error occurs and if the notices are being sent synchronously this will block the request in which the error occurs.

It seems the following might improve the plugin's tolerance to unavailability of the server:
- at startup check if the server is contactable and if not, disable notice sending
- provide a URL that allows notice sending to be enabled/disabled without restarting the application. Obviously this URL would need to be protected so that only admins can access it, but providing this protection would be the responsibility of whatever security mechanism the application is using.

I will submit a pull request if you think this proposal is worthwhile?

**Comment by jonspalmer** [comment]
I'm not sure I love either feature much as they stand.
Startup Check:
If I get unlucky and start my servers when Airbrake isn't responding (or is too slow) then the plugin will deactivate and never recover. I really feel like asynchronous sending is the right way to solve this problem and is the right choice for production apps in general. It handles more cases including slow response from Airbrake. Perhaps the thing we need is a configuration option to control the timeout on the request to the Airbrake host and you could tune that setting down to get a faster fail.

Controller for Enable/Disable
I don't think its right for this plugin to include controllers. You end up picking a url pattern and controller names etc. that each consumer of the plugin might prefer to decide themselves. I completely support the idea that we should have the ability to enable/disable sending notifications programatically while the app is running. I would imaging it is pretty simple to add a method to the AirbrakeService that achieves this. Once that is in place it would be very easy for the consumer of the plugin to write their own controller or command line script to call the service method.

**Comment by ghost** [comment]
## Startup Check:

> If I get unlucky and start my servers when Airbrake isn't responding (or is too slow) then the plugin will deactivate and never recover

If we also add the "Controller for Enable/Disable" feature then it would be possible to enable the plugin again without having to restart the app. However, perhaps your right that sending asynchronously is a "good enough" solution for this problem.

## Controller for Enable/Disable

So it seems we're agreed that it should be possible to enable/disable notifications while the app is running, but there's some disagreement about the exact mechanism used to do that. I proposed providing a controller whereas you think we should just provide a service method and the user can write their own action to call it. There's not a huge difference between these two, so I'll go along with whatever you decide, if it means the difference between getting the pull request accepted or not

However, I don't think your quite right when you say:

> You end up picking a url pattern and controller names etc. that each consumer of the plugin might prefer to decide themselves. 

AFAIK if a plugin provides a controller and doesn't specify any URL pattern for it, then it will use the app's own UrlMappings.groovy. Also, since Grails 2.0 namespaces were introduced that eliminate the possibility of conflicts between application and plugin artifacts.

> I don't think its right for this plugin to include controllers. 

In fact, it already includes a controller, AirbrakeTestController. I realise that the purpose of this controller was to give you an easy way to test the plugin (without having to install it in an app). But this controller is exposed when the plugin is installed. Would there be any value in adding an enable/disable method to this controller?

**Comment by jonspalmer** [comment]
We've partially fix this problem. Adding a callback with success/fail of the notification sending so that the app can decide if to disable sending should be the topic of a new feature request.
