### ISSUE TITLE
logging error without exception doesn't work with Errbit

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#33]
I configured

``` groovy
grails.plugins.airbrake.includeEventsWithoutExceptions = true
```

and tested

``` groovy
log.error 'something went wrong'
```

in an application that logs to Errbit, rather than Airbrake. Errbit responds with a HTTP 500 to the data that is sent. My suspicion is that Errbit doesn't like an empty backtrace element:

``` xml
<backtrace/>
```

but I think if I change it to

``` xml
<backtrace></backtrace>
```

it might work. I guess you don't use Errbit, so I can submit a pull request for this if you wish?

**Comment by jonspalmer** [comment]
That's pretty strange given it is completely valid xml. I guess a pull request if its easy but it might be that airbrake requires the empty tag.

**Comment by ghost** [comment]
Well it's only a hunch, but I vaguely recall Errbit previously rejecting

``` xml
<tag/>
```

but accepting:

``` xml
<tag></tag>
```

If it turns out to be true, I'll check that this doesn't break Airbrake before submitting the pull request. BTW, I think you will need to accept/reject [this pull request](https://github.com/cavneb/airbrake-grails/pull/32), before I can submit a new one.

**Comment by jonspalmer** [comment]
I will take a look. If you create a new pull request from a feature branch they can be considered and pulled independently.

**Comment by ghost** [comment]
I didn't know that (thanks), I'll submit a pull request for this issue on a feature branch if the other pull request has not been reviewed by then.
