### ISSUE TITLE
errors not appearing in airbrake

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#5]
I followed the instructions for integrating v. 0.7.2, but ran into a compilation error because the class MockUserSupplementer could not be found. I eventually discovered that this class is not included in the latest version (0.7.2) of the plugin available in the Grails repo, so I downloaded the .zip from GitHub and used that instead. This resolved the compilation error, but when I run the application and throw an exception, I don't see anything recorded in Airbrake.

My log4j config currently looks like this:

```
log4j = {
  // Example of changing the log pattern for the default console appender:
  appenders {
    def airbrakeAppender = new grails.plugins.airbrake.AirbrakeAppender (
      name: 'airbrake',
      api_key: '19467cfa091f0eb6e51c6350647bf213',
      filtered_keys: ['password'],
      env: ((Environment.current == Environment.PRODUCTION) ? 'production' : 'development'),    
      enabled: true
    )
    airbrakeAppender.addSupplementer(new MockUserSupplementer())
  }

  root {
    debug 'stdout', 'airbrake' // This can be added to any log level, not only 'debug'
  }
}
```

The API key above is the key of the single-user test project I've setup. In case you want to login to Airbrake to check why this isn't working, the details are:

email: domurtag@yahoo.co.uk
password: playboy,83

This is just a test account I'm using to evaluate Airbrake, so I don't mind publishing this info in a public forum :)

**Comment by coderberry** [comment]
Remove the line: `airbrakeAppender.addSupplementer(new MockUserSupplementer())`

I left this in the documentation accidentally. It's only used in the tests for the plugin itself.

Let me know if that fixes the problem.

Eric

**Comment by ghost** [comment]
No, this didn't fix the problem. As this ticket has been closed I'll open a new one.
