### ISSUE TITLE
Docs inconsistent with latest release

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#6]
The information in the docs is not consistent with v. 0.7.2. The docs propose using the configuration below:

```
def isProd = Environment.current == Environment.PRODUCTION

log4j = {
  // Example of changing the log pattern for the default console appender:
  appenders {
    def airbrakeAppender = new grails.plugins.airbrake.AirbrakeAppender (
      name: 'airbrake',
      api_key: 'API_KEY',
      filtered_keys: ['password'],
      env: ((Environment.current == Environment.PRODUCTION) ? 'production' : 'development'),
      enabled: true
    )
  }

  root {
    debug 'stdout', 'airbrake' // This can be added to any log level, not only 'debug'
  }
}
```

But the AirbrakeAppender class does not have an "enabled" property. Also in the config above, the "isProd" variable is never used.

Furthermore, the docs refer to a test controller that is available at:

```
http://localhost:8080/airbrakeTest/throwException
```

This is not present in release 0.7.2, but is present in the head of the git repository, so perhaps you need to release this as a new version?

**Comment by jonspalmer** [comment]
this was fixed a while ago
