### ISSUE TITLE
Grails 1.3.X

### ISSUE THREAD

**Issue by ghost** [coderberry/airbrake-grails#8]
I would like to use this plugin in a Grails 1.3.7 app. I can't use the current release because AirbrakeGrailsPlugin.groovy declares

```
def grailsVersion = "2.0.0 > *"
```

If I were to fork the plugin, and change this to

```
def grailsVersion = "1.3.7 > *"
```

are you aware of any reason why the plugin wouldn't work, or to put the question another way, are you actually using any Grails 2.X specific features?

**Comment by coderberry** [comment]
To be honest, I have no idea if it will work in 1.3.7. You are more than welcome to give it a shot. Let me know if it works.

**Comment by ghost** [comment]
There are a couple of small changes necessary for this plugin to work with Grails 1.3.X apps. First of all you need to change the declaration in BuildConfig.groovy to something like:

```
def grailsVersion = "1.3.5 > *"
```

Also in GroovyNoticeSerializer you need to rewrite the filterParameters method because the version of Groovy used in Grails 1.3.X does not add a countEntries method to the Map class.

If you replace the current implementation of this method with the implementation below, then everything seems to work fine in Grails 1.3.X

```
    private Map filterParameters(Map params, AirbrakeNotifier airbrakeNotifier) {

        def filteredParams = [:]

        params.each { k, v ->
            def filteredValue = airbrakeNotifier.filteredKeys?.any {
                // println "key $k, filter $it"
                k =~ it } ? "FILTERED" : v.toString()

            filteredParams[k] = filteredValue
        }
        filteredParams
    }
```

If you were willing to make these changes in order to accommodate Grails 1.3.X users it would be much appreciated, otherwise I guess I'll just have to fork the plugin and make these changes in the fork.

**Comment by jonspalmer** [comment]
I'd be a little resistant to making changes like this to work past the lack of collectEntries. At some point we have to put a stake in the ground and give ourselves a baseline to work from. I believe that 2.x is the appropriate place to offer support from for now.

**Comment by ghost** [comment]
Obviously it's your call, but I don't see that there's any downside to making this change. The upside is that more projects can use the plugin, surely this is a good thing?

**Comment by jonspalmer** [comment]
Part of the issue is testability to maintain backwards compatability and that results in real overhead as we create new features to always have to test in old versions of Grails/Groovy. At some point that cost outweighs the benefits of supporting legacy versions.

**Comment by ghost** [comment]
That's a fair point. What about creating a separate branch (that uses a different plugin version, e.g. 0.7.2-grails1) for Grails 1. I'm willing to maintain this branch if the idea is approved.

**Comment by jonspalmer** [comment]
sure that seems reasonable

**Comment by ghost** [comment]
Great, I'll create a pull request
